### ISSUE TITLE
Decode error bitmasks

### ISSUE THREAD

**Issue by syssi** [syssi/esphome-daly-bms#13]
It's hard to guess the byte-order of the bitmasks. I would be happy about some testing. I will provide all required steps / give some guidance.

**Comment by syssi** [comment]
Do you have the chance to cool down the temperature probe of the BMS to 0 degrees? I would like to trigger a protection state of the BMS to get an idea of the byte order of the registers holding the protection bits.

**Comment by felipecrs** [comment]
I can surely test this for you. But do you have any idea on how could I cool down one temperature sensor o this degree?

**Comment by syssi** [comment]
Is there no external temperature probe to put in a glass of ice water?

**Comment by felipecrs** [comment]
Yes, I can do it. I was wondering whether the sensor is waterproof or not, but I guess it should not be a problem.

I can test it whenever you want.
