### ISSUE TITLE
Verify Mosfet controls are working properly

### ISSUE THREAD

**Issue by syssi** [syssi/esphome-daly-bms#24]

**Comment by syssi** [comment]
@felipecrs In general the `charge` and `discharge` switch is able to control the mosfet of the BMS. Correct? Just the initial state and a update routine is missing. 

I would like to close this issue as soon this is verified.

**Comment by felipecrs** [comment]
Just tested and both are working fine. I can switch off and on the charging and discharging mos, and the sensor is updated in the next read.

I can also confirm it turned on and off through the Android app.
