### ISSUE TITLE
Add status text sensor

### ISSUE THREAD

**Issue by felipecrs** [syssi/esphome-daly-bms#30]
As in the Excel modbus manual:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/felip/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/felip/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#467886" vlink="#96607D">

R | charge/discharge   status | 0--65535 | 0=stationary，1=charging，2=discharging
-- | -- | -- | --

</body>

</html>

**Comment by syssi** [comment]
We could use this register to add the missing sign of the current sensor. Do you think there is a need for a charging/discharging indicator nevertheless?

**Comment by syssi** [comment]
I'm talking about this sensor:

https://github.com/syssi/esphome-daly-bms/blob/main/esp32-ble-example.yaml#L93-L94

And want to mitigate this issue:

https://github.com/syssi/esphome-daly-bms/issues/1#issuecomment-2469140633

Is my understand correct: The DALY app shows always a positive current while charging & discharging?

**Comment by felipecrs** [comment]
Well, my sensor is showing negative values:

![image](https://github.com/user-attachments/assets/e8f9c8e7-e370-4d80-928c-ace85eda34cd)

**Comment by felipecrs** [comment]
The power one is always positive:

![image](https://github.com/user-attachments/assets/2bfceaa7-f4e7-44a1-ac45-aab40b2650ba)

**Comment by felipecrs** [comment]
I'll try it now, unplugging my power.

**Comment by syssi** [comment]
Thanks! I will prepare a fix to sign the power sensors.

**Comment by felipecrs** [comment]
Unplugged the power:

![image](https://github.com/user-attachments/assets/b54c9c3c-e1de-4cc5-a14c-0649700f5b6c)

**Comment by felipecrs** [comment]
Confirmed to work now, after #32:

![image](https://github.com/user-attachments/assets/3307a703-1c9f-483a-bf58-751d4a5a00cb)

**Comment by syssi** [comment]
Awesome! Thanks for testing!
